# 🛡️ This file is MIT licensed. See LICENSE in the repository.
# -------------------------------------------------------------------------------------
# 🛡️ NOTE: For most repositories, you should strongly consider using GitHub's official code security tools
# (such as CodeQL and Dependabot), which are free for public repositories.
# See https://github.com/features/security for details.
#
# ⚠️ DISCLAIMER:
# This workflow is a community-developed tool and is not affiliated with, endorsed by, or officially supported by GitHub or the CodeQL team.
# It is provided as-is for public use.
# This workflow should not be considered an official GitHub or CodeQL product.
# Use at your own discretion.
#
# 🚀 Workflow:
# - Runs CodeQL analysis on a repository
# - Scans for security and quality issues
# - Automatically creates a GitHub issue for EACH new finding
# - Attaches the specific SARIF finding data to each issue
# - Is reusable and can be called from other workflows
#
# 🧩 How it works:
# - Runs CodeQL analysis for the specified language.
# - Generates a SARIF report with security and quality findings.
# - Processes the SARIF file and for each result:
#   - Deduplicates findings using a hash of its rule, location, and message.
#   - Creates a GitHub issue for each new finding, labeled 'codeql-finding'.
#   - Attaches the specific SARIF result for that finding in a collapsible section.
#   - Skips open issues and respects closed ones (does not reopen).
# - Can be called from other workflows using 'workflow_call'.
# -------------------------------------------------------------------------------------
# 🧪 Usage Example
#
# To use this action in your workflow, add the following to your workflow YAML:
#
# name: 'CodeQL Analyser'
#
# permissions:
#   security-events: write
#   actions: read
#   contents: read
#   issues: write
#
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main
#   schedule:
#     - cron: '30 1 * * 0'
#
# jobs:
#   analyze:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Run CodeQL Analysis and Create Issues
#         uses: pixpilot/github/actions/codeql-analyzer@main
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           languages: javascript # Comma-separated list of languages e.g., javascript,python
#           config-file: .github/codeql/codeql-configuration.yml
#           debug: true
# -------------------------------------------------------------------------------------

name: CodeQL Issue Maker
description: 'Runs CodeQL analysis, filters files, and creates GitHub issues for findings.'

inputs:
  languages:
    description: >-
      A comma-separated list of CodeQL languages to analyze.
      For example: 'javascript,python,java'
    required: false
    default: javascript
  source-root:
    description: Path of the root source code directory, relative to $GITHUB_WORKSPACE.
    required: false
  ram:
    description: >-
      The amount of memory in MB that can be used by CodeQL extractors.
      By default, CodeQL extractors will use most of the memory available in the system.
    required: false
  threads:
    description: >-
      The number of threads that can be used by CodeQL extractors.
      By default, CodeQL extractors will use all the hardware threads available in the system.
    required: false
  debug:
    description: >-
      Enable debugging mode.
      This will result in more output being produced which may be useful when debugging certain issues.
    required: false
    default: 'false'
  config:
    description: Configuration passed as a YAML string in the same format as the config-file input. This takes precedence over the config-file input.
    required: false
  config-file:
    description: 'Path to CodeQL configuration file (e.g., .github/codeql/codeql-configuration.yml)'
    required: false
  qls-profile:
    description: 'Comma-separated list of CodeQL QLS profiles to use (e.g., security-and-quality,security-extended)'
    required: false
    default: security-and-quality
  token:
    description: GITHUB_TOKEN for creating issues
    required: true

runs:
  using: node20
  main: dist/index.js
