import type { CodeQLResult } from '../../types';

/** Hard limit enforced by the GitHub issues API. */
const ISSUE_BODY_LIMIT = 65536;
/** Head-room so a body never lands exactly on the API limit. */
const RESERVED_MARGIN = 1024;
const BODY_BUDGET = ISSUE_BODY_LIMIT - RESERVED_MARGIN;

const MAX_MESSAGE_LENGTH = 4000;
const MAX_LOCATIONS = 50;
/** Below this, a details block holds too little to be worth rendering. */
const MIN_JSON_BUDGET = 1000;
const JSON_INDENT = 2;

/** SARIF fields that dominate the payload of dataflow findings. */
const VERBOSE_FIELDS = ['codeFlows', 'relatedLocations'] as const;

function truncate(text: string, max: number, note: string): string {
  if (text.length <= max) return text;

  return `${text.slice(0, max)}\n${note}`;
}

function buildLocationsList(locations: CodeQLResult['locations']): string {
  if (!locations || locations.length === 0) return '_No locations reported._';

  const shown = locations.slice(0, MAX_LOCATIONS);
  let list = '';
  for (const loc of shown) {
    const locFile = loc.physicalLocation.artifactLocation.uri;
    const locLine = loc.physicalLocation.region.startLine;
    const locMessage = loc.message ? ` - ${loc.message.text}` : '';
    list += `- **File:** \`${locFile}\` **Line:** ${locLine}${locMessage}\n`;
  }

  const omitted = locations.length - shown.length;
  if (omitted > 0) {
    list += `\n_… and ${omitted} more location(s), omitted to keep this issue within GitHub's size limit._\n`;
  }

  return list;
}

/**
 * Renders the SARIF result as JSON that fits `budget`, dropping the most verbose
 * fields first and only hard-truncating as a last resort.
 */
function buildDetails(result: CodeQLResult, budget: number): string {
  if (budget < MIN_JSON_BUDGET) {
    return "_SARIF finding details omitted: the finding is too large to include within GitHub's issue size limit. Re-run the analysis to inspect the full result._";
  }

  const full = JSON.stringify(result, null, JSON_INDENT);
  const details = (json: string, note?: string): string =>
    [
      '<details>',
      `<summary>Click to view SARIF finding details</summary>`,
      ...(note !== undefined && note !== '' ? ['', note] : []),
      '',
      '```json',
      json,
      '```',
      '</details>',
    ].join('\n');

  if (details(full).length <= budget) return details(full);

  // Drop the verbose fields (code flows are typically 90%+ of a large finding) and
  // summarise what was removed, rather than cutting the JSON mid-structure.
  const summarised: Record<string, unknown> = { ...result };
  const dropped: string[] = [];
  for (const field of VERBOSE_FIELDS) {
    const value = result[field];
    if (value !== undefined) {
      delete summarised[field];
      dropped.push(`${field} (${value.length} entries)`);
    }
  }

  if (dropped.length > 0) {
    const note = `> ⚠️ Trimmed to fit GitHub's issue size limit. Omitted: ${dropped.join(', ')}. The rule and locations above identify the finding.`;
    const trimmed = JSON.stringify(summarised, null, JSON_INDENT);
    const rendered = details(trimmed, note);
    if (rendered.length <= budget) return rendered;
  }

  // Still too large: cut the JSON itself, leaving room for the fence and note.
  const note = `> ⚠️ Truncated to fit GitHub's issue size limit.`;
  const overhead = details('', note).length;
  const jsonBudget = Math.max(budget - overhead, 0);

  return details(truncate(full, jsonBudget, '… (truncated)'), note);
}

/**
 * Builds an issue body that is guaranteed to fit GitHub's 65536-character limit,
 * shrinking the least useful content first.
 */
export function formatIssueBody(result: CodeQLResult, findingHash: string): string {
  const { ruleId, message } = result;
  const msg = truncate(message.text, MAX_MESSAGE_LENGTH, '… (message truncated)');

  const header = [
    `## 🚨 Security Alert: ${ruleId}`,
    `<strong>Message:</strong> ${msg}`,
    `<strong>Finding ID:</strong> <code>${findingHash}</code>`,
    '---',
    '### Vulnerability Locations',
    buildLocationsList(result.locations),
    '---',
  ].join('\n\n');

  const footer = [
    '',
    '---',
    '*This issue was automatically generated by a custom CodeQL workflow.*',
  ].join('\n\n');

  const separators = '\n\n'.length;
  const detailsBudget = BODY_BUDGET - header.length - footer.length - separators;
  const body = [header, buildDetails(result, detailsBudget), footer].join('\n\n');

  // Safety net: nothing leaves this function over the API limit, whatever the input.
  return body.length > ISSUE_BODY_LIMIT ? body.slice(0, ISSUE_BODY_LIMIT) : body;
}

export { ISSUE_BODY_LIMIT };
